### ISSUE TITLE
profiles/IMCE/IMCE.owl2-mof2.mdzip incorrectly mounts profiles/SSCAEProjectUsageIntegrityProfile.mdzip

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/gov.nasa.jpl.imce.profileGenerator.application#1]
None of the profiles & libraries should mount the profiles/SSCAEProjectUsageIntegrityProfile.mdzip from the [PUIC](https://github.com/JPL-IMCE/gov.nasa.jpl.magicdraw.projectUsageIntegrityChecker) to avoid forcing an unnecessary dependency on the PUIC itself.

**Comment by sjiherzig** [comment]
Not sure how that happened - will fix!

**Comment by sjiherzig** [comment]
Fixed in version 2.5.2 - see commit 9b570c6c94d26c9fdf2a4a10eb68df374dee7d88 #
